# Generated by Django 2.2 on 2019-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplechoice', '0002_auto_20190506_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
