# Generated by Django 2.2 on 2019-05-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplechoice', '0005_auto_20190506_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated_at',
        ),
    ]
